#!/bin/sh

# This hook builds the client typescript and replaces {{pre-push:branch}}
# in every build file with the destination branch

src_userscript="client/moodle_utils.user.ts"
tsconfig="client/tsconfig.json"
out_userscript="client/build/moodle_utils.user.js"

# shellcheck disable=SC2034
while read -r local_ref local_sha remote_ref remote_sha
do
	# do nothing if userscript unchanged
	if git diff --quiet "$local_sha" "$remote_sha" -- $src_userscript ; then
		continue
	fi
	echo "pre-push: change to $src_userscript detected" >&2


	# build
	echo "pre-push: building $tsconfig" >&2
	tsc -p "$tsconfig" || exit 1

	# substitute {{pre-push:branch}}
	echo "pre-push: substitute in $out_userscript: {{pre-push:branch}} -> <remote-branch-name>" >&2
	branch=$(echo "$remote_ref" | cut -d / -f 3)
	sed -i -e "s/{{pre-push:branch}}/$branch/g" -- "$out_userscript" || exit 2

	echo "pre-push: amending last commit" >&2
	(git add . && git commit --amend --no-edit) || exit 3
done

exit 0
