#!/bin/sh

# This hook builds the client typescript and replaces {{pre-push:branch}}
# in every build file with the destination branch

# do nothing if userscript unchanged
if ! git ls-files -m | grep -e '^client/moodle_utils\.user\.ts$'; then
	exit 0
fi

# shellcheck disable=SC2034
while read -r local_ref local_sha remote_ref remote_sha
do
	# build
	repo_root=$(git rev-parse --show-toplevel)
	cd "$repo_root/client" || exit 1
	tsc || exit 1

	# navigate to build dir
	out_dir=$(tsc --showConfig | grep -oP '(?<="outDir": ")[^"]*' || echo .)
	cd "$out_dir" || exit 2

	# substitute {{pre-push:branch}}
	branch=$(echo "$remote_ref" | cut -d / -f 3)
	sed -i -e "s/{{pre-push:branch}}/$branch/g" -- *.user.js || exit 3

	git add . || exit 4
	git commit -m "substituted {{pre-push:branch}} with branch name" || exit 5
done

exit 0
